### ISSUE TITLE
Annotation @History is not working! SQL ERROR

### ISSUE THREAD

**Issue by HannahJSwystun** [payintech/play-ebean#1]
Hello,

I am using the last version of io.ebean, I think that the SQL statements created automatically when adding @HISTORY annotation in a model has a fault because 
1- when Updating a table for the first time 
=> this update **the model** + adding new row in **model_history**

2- when updating the same row in a second time => KO 
because model_history can't duplicate the key id two or many times....

Ex : 
![sans titre](https://cloud.githubusercontent.com/assets/20491664/22304617/10d8ed78-e330-11e6-9495-5bf326dbd9cb.png)

**Comment by thibaultmeyer** [comment]
Hi,

thank you for using our version of play-ebean. This issue is more related to Ebean itself rather than Play module.

According to the post on [Ebean Google group](https://groups.google.com/forum/#!topic/ebean/C3AtLLBZy3w), It seem you have resolved your issue.


Sincerly.
