### ISSUE TITLE
Support for sbt 1.4.x

### ISSUE THREAD

**Issue by petahathub** [payintech/play-ebean#14]
Hi,

I have:
Play Framework 2.7.7 on java,
"com.payintech" % "sbt-play-ebean" % "19.10u1",
scala 2.12.12

and i am playing with new sbt 1.4.5.

But the compilation fails with error, about which i think it is correlated with ebean:

`
[fpds] $ last Compile / manipulateBytecode
[error] java.lang.ClassCastException: class sbt.internal.inc.MappedVirtualFile c
annot be cast to class java.io.File (sbt.internal.inc.MappedVirtualFile is in un
named module of loader sbt.internal.MetaBuildLoader @78c7f9b3; java.io.File is i
n module java.base of loader 'bootstrap')
[error]         at scala.collection.TraversableOnce$folder$1$.apply(TraversableO
nce.scala:187)
[error]         at scala.collection.TraversableOnce$folder$1$.apply(TraversableO
nce.scala:185)
[error]         at scala.collection.immutable.HashMap$HashMapKeys.$anonfun$forea
ch$1(HashMap.scala:149)
[error]         at scala.collection.immutable.HashMap$HashMap1.foreachEntry(Hash
Map.scala:395)
[error]         at scala.collection.immutable.HashMap$HashTrieMap.foreachEntry(H
ashMap.scala:728)
[error]         at scala.collection.immutable.HashMap$HashTrieMap.foreachEntry(H
ashMap.scala:728)
[error]         at scala.collection.immutable.HashMap$HashMapKeys.foreach(HashMa
p.scala:149)
[error]         at scala.collection.TraversableOnce.foldLeft(TraversableOnce.sca
la:189)
[error]         at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.sc
ala:184)
[error]         at scala.collection.AbstractTraversable.foldLeft(Traversable.sca
la:108)
[error]         at play.ebean.sbt.PlayEbean$.$anonfun$ebeanEnhance$1(PlayEbean.s
cala:103)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFuncti
ons.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.sc
ala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(Con
currentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64
)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java
:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call
(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java
:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(T
hreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(
ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:834)`

In PlayEbean.scala you do some manipulations with timestamps, it is probably in conflict with sbt.

sbt 1.3.13 works fine.

**Comment by JFCote** [comment]
I have this problem. No update since last year? Can we do something to help release a version with a fix? This plugin is useless unless this is fixed. Thanks

**Comment by mkurz** [comment]
See my comment regarding this problem here: https://github.com/payintech/play-ebean/issues/17#issuecomment-1000439794

**Comment by PierreAdam** [comment]
Fixed in `22.03RC1`
