### ISSUE TITLE
Remove play-enhancer as it is reached End of Life and will not work in sbt 1.4 and later

### ISSUE THREAD

**Issue by almothafar** [payintech/play-ebean#16]
As you can see here https://github.com/playframework/play-enhancer 

> End of Life
> The active Playframework contributors consider this repository has reached End of Life and archived it.
> 
> This repository is not being used anymore and won't get any further updates.
> 
> Thank you to all contributors that worked on this repository!

So it will not work with sbt 1.4 and later, this plugin will be useless if you want to use newer sbt, please remove as the original plugin is done that as well.

**Comment by PierreAdam** [comment]
Version `22.03RC1` is now updated without PlayEnhancer
