### ISSUE TITLE
Migration on latest versions (17.05+)

### ISSUE THREAD

**Issue by corrspt** [payintech/play-ebean#3]
Hi, thanks for all the hard work on play-ebean :)

I wanted to ask something, regarding generation of DBMigrations. I've been using a class like this to generate offline migrations.

```java
public class Migration {

	public static void main(String[] args) throws IOException {

		loadEnhancerAgent();

		configureEbeanServer();

		DbMigration dbMigration = new DbMigration();

		// set path that the migration xml and ddl is located (where to read the existing schema)
		dbMigration.setPathToResources("ebeanddl");
		//Then there's the ebean.migration.resourcePath which tells it where to write

		dbMigration.setPlatform(Platform.POSTGRES);
		dbMigration.generateMigration();

	}

	private static void configureEbeanServer() {
		ServerConfig config = new ServerConfig();
		config.setName("default");
		config.loadFromProperties();
		config.setCurrentUserProvider(new UserIdProvider());

		DataSourceConfig dsConfig = new DataSourceConfig();
		dsConfig.setUsername("password");
		dsConfig.setPassword("password");
		dsConfig.setDriver("org.postgresql.Driver");
		dsConfig.setUrl("jdbc:postgresql://localhost:5432/database");
		config.setDataSourceConfig(dsConfig);
		config.setDefaultServer(true);

		EbeanServerFactory.create(config);
	}

	private static void loadEnhancerAgent() {
		if (!AgentLoader.loadAgentFromClasspath("ebean-agent",
				"debug=9;packages=com.project.models.**")) {
			throw new RuntimeException("Could not load the Ebean Enhancer Agent");
		}
	}

}
```

I've tried upgrading to the last two versions (17.05 and 17.06) and when I run this script it blows up midway saying the a particular bean is not "enhanced. I'm kind of suspecting on the Play Framework upgrade that play-ebean does (I'm on 2.5.12 from play-ebean 17.04)

I'm not sure this is the best way to generate migrations, but since I use sbt and not maven, it was the only way I could find to generate migrations using Ebean.

Appreciate any help 👍  Once again, thanks a lot for all the effort.

**Comment by thibaultmeyer** [comment]
Hello @corrspt ,

It seems you come from the release17.04; is it working well ? The only changes on the release 17.05 are the Ebean dependencies updated to prior version. Have you try to put your code into a Controller rather than a "standard" Maven/Java application?

If you are using PlayFramework 2.5.x or 2.6.0 with our play-ebean plugin, I think you should use Play Evolutions for the database tables (create, update, ...) and using Ebean DB migration only as "database seed".  In a futur release, it would be possible to use play-ebean without Evolutions.


PS: The version 17.06 is for Play 2.6.0 and later (we are migrated to Play 2.7 some internal projects this week).

**Comment by corrspt** [comment]
Hi @0xbaadf00d 

Thanks for the quick reply. Yes I'm using 17.04 and it's working very well 👍

I'm using 17.04 and overriding the Ebean version to 10.3.1 (the one in 17.05) and it's working great. I'm using Ebean to generate the migrations, but to apply them I'm using flyway-db (through play-flyway).

In my `plugins.sbt` I have
`addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.5.9")`

I haven't tried to put the migration code on a controller, that's an interesting idea. Will check that.

but through play-ebean I get `play 2.5.12`.  These two facts (that in 17.05 the play-framework is upgraded to 2.5.15 and the fact that I'm using the latest ebean with success makes my suspicious of the play framework)..

I've never looked at play evolutions, I'll have to look at that (I'd prefer to keep my current system, but I'm always open to new ideas). Thanks for the tip on 17.06, I'll have to check that once I can get to 17.05 ;)
